management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081
  tomcat:
    mbeanregistry:
      enabled: true
    threads:
      max: 200
      min-spare: 20
  shutdown: graceful

spring:
  application:
    name: federated-catalogue-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres #catalogdb
    username: postgres
    password: postgres
    platform: postgresql
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 5
      maximumPoolSize: 25
  liquibase:
    change-log: classpath:/liquibase/master-changelog.xml
  main:
    allow-bean-definition-overriding: true    
  mvc:
    log-request-details: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://key-server:8080/realms/gaia-x
#          jwk-set-uri: http://key-server:8080/realms/gaia-x/protocol/openid-connect/certs

scheduler:
  sd:
    cron:
      expression: 0 1 0 * * *

openapi:
  gaiaXCatalogue:
    base-path: ""

springdoc:
  api-docs:
    path: /api/docs
    enabled: true

keycloak:
  auth-server-url: http://key-server:8080
  realm: gaia-x
  resource: federated-catalogue
  credentials:
    secret: vZo1equicRl1UdxJDWCNNJWe6vJcm2Cg

datastore:
  file-path: target

graphstore:
  uri: bolt://localhost:7687
  user: neo4j
  password: 12345

logging:
  level:
    root: INFO
    eu.gaiax.difs.fc: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
#    org.springframework.web.client.RestTemplate: DEBUG

federated-catalogue:
  scope: runtime
  file-store:
    sd:
      location: sdFiles
    schema:
      location: schemaFiles
    context-cache:
      location: contextCacheFiles
