kind: PersistentVolume
apiVersion: v1
metadata:
  name: fc-postgres-pv-volume
  labels:
    type: local
    app: fc-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fc-postgres-pv-claim
  labels:
    app: fc-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi