version: '3.7'

services:
  keycloak:
    container_name: "federated-catalogue-keycloak"
    environment:
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
      PROXY_ADDRESS_FORWARDING: "${PROXY_ADDRESS_FORWARDING}"
    image: "quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}"
    ports:
      - "8080:8080"
    networks:
      - "gaia-x"
    restart: unless-stopped
    extra_hosts:
      - "auth-server:${AUTH_SERVER_HOST_GATEWAY}"
    volumes:
      - "../keycloak/providers:/opt/keycloak/providers"
      - "../keycloak/realms:/tmp/import"
    command:
      [
          'start-dev --auto-build',
          '-Dkeycloak.migration.action=import',
          '-Dkeycloak.migration.provider=dir',
          '-Dkeycloak.migration.dir=/tmp/import',
          '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
          '-Dkeycloak.profile.feature.upload_scripts=enabled',
          '--log-level=DEBUG,io.quarkus:INFO,liquibase:INFO,org.hibernate:INFO,org.infinispan:INFO,org.keycloak.services.scheduled:INFO,org.keycloak.transaction:INFO,io.netty.buffer.PoolThreadCache:INFO,org.keycloak.models.sessions.infinispan:INFO'
      ]
  server:
    build:
      context: ..
      dockerfile: ./fc-service-server/Dockerfile
    container_name: "federated-catalogue-server"
    image: "${CI_REGISTRY}/${SERVER_ARTIFACT}:${SERVER_VERSION}"
    ports:
      - "8081:8081"
    networks:
      - "gaia-x"
    restart: unless-stopped

#    we will enable this once demo-portal web app is ready
#  portal:
#    container_name: "federated-catalogue-portal"
#    image: "${CI_REGISTRY}/${PORTAL_ARTIFACT}:${PORTAL_VERSION}"
#    ports:
#      - "8082:8082"
#    networks:
#      - "gaia-x"
#    restart: unless-stopped

networks:
  gaia-x:
    driver: "bridge"