version: '3.7'

services:
  keycloak:
    container_name: "federated-catalogue-keycloak"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      PROXY_ADDRESS_FORWARDING: "true"
    image: "quay.io/keycloak/keycloak:17.0.1"
    ports:
      - "8080:8080"
    networks:
      - "gaia-x"
    restart: unless-stopped
    volumes:
      - "../keycloak/providers:/opt/keycloak/providers"
      - "../keycloak/realms:/tmp/import"
    command:
      [
          'start-dev --auto-build',
          '-Dkeycloak.migration.action=import',
          '-Dkeycloak.migration.provider=dir',
          '-Dkeycloak.migration.dir=/tmp/import',
          '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
          '-Dkeycloak.profile.feature.upload_scripts=enabled',
          '--log-level=DEBUG,io.quarkus:INFO,liquibase:INFO,org.hibernate:INFO,org.infinispan:INFO,org.keycloak.services.scheduled:INFO,org.keycloak.transaction:INFO,io.netty.buffer.PoolThreadCache:INFO,org.keycloak.models.sessions.infinispan:INFO'
      ]

  server:
    container_name: "federated-catalogue-server"
#    image: "${CI_REGISTRY}/fc-service-server:0.0.1-SNAPSHOT"
    build:
      context: ../fc-service-server
      dockerfile: Dockerfile
    environment:
      KEYCLOAK_CREDENTIALS_SECRET: "${FC_CLIENT_SECRET}"
    ports:
      - "8081:8081"
    networks:
      - "gaia-x"
    extra_hosts:
      - "key-server:host-gateway"
      - "localhost:127.0.0.1"
    restart: unless-stopped

  portal:
    container_name: "federated-catalogue-portal"
#    image: "${CI_REGISTRY}/demo-portal:0.0.1-SNAPSHOT"
    build:
      context: ../demo-portal
      dockerfile: Dockerfile
    environment:
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FC_CLIENT_OIDC_CLIENT_SECRET: "${FC_CLIENT_SECRET}"
    ports:
      - "8088:8088"
    networks:
      - "gaia-x"
    extra_hosts:
      - "key-server:host-gateway"
      - "localhost:host-gateway"
    restart: unless-stopped

  postgres:
    image: postgres:latest
    restart: always
    environment:
#      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data/

networks:
  gaia-x:
    driver: "bridge"