server:
  port: 8081
#server.servlet.context-path= /test

#graphstore:
#  user: neo4j
#  password: 12345
#  uri: bolt://localhost:7687

spring:  
  jpa:  
    hibernate:  
      ddl-auto: create  
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
#    generate-ddl = true
  datasource:  
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/postgres"  
    username: postgres
    password: postgres
    platform: postgresql

  neo4j:
    uri: bolt://localhost:7687
  data:
    neo4j:
      username: neo4j
      password: 12345

logging:
  level:
    root: DEBUG
    eu.gaiax.test: DEBUG
    org.springframework: DEBUG
