apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: neo4j-db
  name: neo4j-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j-db
  template:
    metadata:
      labels:
        app: neo4j-db
    spec:
      initContainers:
        - name: init-plugins
          image: "appropriate/curl:latest"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: neo4j-plugins
              mountPath: /plugins
          command:
            - "/bin/sh"
            - "-c"
            - |
              curl -L https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.4.0.10/apoc-4.4.0.10-all.jar -O
              curl -L https://graphdatascience.ninja/neo4j-graph-data-science-2.2.2.jar -O
              curl -L https://github.com/neo4j-labs/neosemantics/releases/download/4.4.0.2/neosemantics-4.4.0.2.jar -O
              cp -R apoc-4.4.0.10-all.jar /plugins
              cp -R neo4j-graph-data-science-2.2.2.jar /plugins
              cp -R neosemantics-4.4.0.2.jar /plugins
      containers:
        - image: neo4j:4.4.12
          name: neo4j
          env:
            - name: NEO4J_AUTH
              value: "neo4j/12345"
            - name: NEO4J_dbms_security_procedures_unrestricted
              value: "gds.*,apoc.*,n10s.*"
            - name: NEO4J_dbms_directories_plugins
              value: "plugins"
          ports:
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
            - containerPort: 7473
              name: https
          volumeMounts:
            - name: neo4j-plugins
              mountPath: "/var/lib/neo4j/plugins"
            - name: neo4j-data
              mountPath: "/var/lib/neo4j/data"
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-data-claim
        - name: neo4j-plugins
          persistentVolumeClaim:
            claimName: neo4j-plugin-claim